PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE entries (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  slug          TEXT NOT NULL UNIQUE,
  date_month    INTEGER NOT NULL CHECK (date_month BETWEEN 1 AND 12),
  date_day      INTEGER NOT NULL CHECK (date_day BETWEEN 1 AND 31),
  date_type     TEXT NOT NULL DEFAULT 'fixed' CHECK (date_type IN ('fixed', 'movable')),
  name_pl       TEXT NOT NULL,
  name_en       TEXT NOT NULL,
  description_pl TEXT,
  region        TEXT NOT NULL CHECK (region IN ('global','europe','poland','americas','asia','oceania','africa')),
  category      TEXT NOT NULL CHECK (category IN ('sweet','savory','beverage','fruit','vegetable','dairy','meat','grain','seafood','dish','other')),
  popularity    INTEGER NOT NULL DEFAULT 50 CHECK (popularity BETWEEN 0 AND 100),
  image_key     TEXT,
  sources       TEXT,
  verified      INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT DEFAULT CURRENT_TIMESTAMP,
  updated_at    TEXT DEFAULT CURRENT_TIMESTAMP
, date_end_month INTEGER, date_end_day   INTEGER, recurrence     TEXT NOT NULL DEFAULT 'yearly'
  CHECK (recurrence IN ('yearly', 'none')), entry_year     INTEGER, source_type    TEXT NOT NULL DEFAULT 'curated'
  CHECK (source_type IN ('curated', 'admin')), created_by     TEXT, movable_note   TEXT);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(86,'swiatowy-dzien-gorzkiej-czekolady',1,10,'fixed','Dzień Gorzkiej Czekolady','Bittersweet Chocolate Day','Polskie święto promujące zdrowotne właściwości gorzkiej czekolady.','poland','sweet',60,NULL,'["https://kalendarzroku.pl/kalendarz-swiat/dzien-gorzkiej-czekolady/"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(87,'swiatowy-dzien-spaghetti',1,4,'fixed','Dzień Spaghetti','National Spaghetti Day','Święto najpopularniejszych włoskich makaronów, chętnie obchodzone także w Polsce.','global','grain',66,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(88,'dzien-bitej-smietany',1,5,'fixed','Dzień Bitej Śmietany','Whipped Cream Day','Słodkie święto bitą śmietaną — deserowej królowej dodatków.','americas','dairy',48,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(89,'swiatowy-dzien-wegetarian',10,1,'fixed','Światowy Dzień Wegetarian','World Vegetarian Day','Ustanowiony w 1977 r. przez North American Vegetarian Society — początek Miesiąca Wegetariańskiego.','global','vegetable',62,NULL,'["https://en.wikipedia.org/wiki/List_of_food_days"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(90,'dzien-pikantnych-potraw',1,16,'fixed','Dzień Pikantnych Potraw','International Hot and Spicy Food Day','Święto dla miłośników ostrych przypraw.','global','savory',55,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(91,'dzien-popcornu',1,19,'fixed','Dzień Popcornu','Popcorn Day','Święto ulubionej przekąski kinowych wieczorów.','americas','grain',62,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(92,'dzien-bigosu',1,20,'fixed','Dzień Bigosu','Bigos (Hunter''s Stew) Day','Święto królewskiego polskiego dania z kapusty i mięsa.','poland','dish',70,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(93,'dzien-sera',1,20,'fixed','Dzień Sera','Cheese Lovers Day','Święto miłośników serów, w Polsce promuje także sery regionalne.','global','dairy',74,NULL,'["https://nationaltoday.com"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(94,'swiatowy-dzien-pizzy-wlochy',1,17,'fixed','Światowy Dzień Pizzy (włoski)','World Pizza Day (Italian)','Włoska data święta pizzy — 17 stycznia, rocznica konsekracji bazyliki św. Antoniego Pustelnika, patrona pizzerzy.','europe','dish',88,NULL,'["https://pizzeria-ewa.pl/kiedy-jest-dzien-pizzy/"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(95,'dzien-nalesnika',2,2,'fixed','Dzień Naleśnika','Pancake Day','Światowe święto naleśników, w Polsce często łączone z tłustym czwartkiem.','global','sweet',72,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(96,'dzien-nutelli',2,5,'fixed','Światowy Dzień Nutelli','World Nutella Day','Święto najsłynniejszej pasta orzechowej, ustanowione przez fanów w 2007 r.','global','sweet',78,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(97,'miedzynarodowy-dzien-pizzy',2,9,'fixed','Międzynarodowy Dzień Pizzy','International Pizza Day','Data, która dominuje w komunikacji marketingowej polskich pizzerii — 9 lutego.','poland','dish',92,NULL,'["https://pizzeria-ewa.pl/kiedy-jest-dzien-pizzy/","https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(98,'swiatowy-dzien-roslin-straczkowych',2,10,'fixed','Światowy Dzień Roślin Strączkowych','World Pulses Day','Ustanowiony przez ONZ, promuje wartości odżywcze roślin strączkowych.','global','vegetable',58,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/","https://www.un.org/en/observances"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(99,'dzien-tosta',2,26,'fixed','Dzień Tosta','National Toast Day','Święto tostowego chleba.','europe','grain',45,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(100,'swiatowy-dzien-pieroga',2,25,'fixed','Światowy Dzień Pieroga','World Pierogi Day','Święto polskiego dania narodowego, coraz szerzej obchodzone na świecie.','poland','dish',85,NULL,'["https://pierogiday.com"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(101,'dzien-platkow-sniadaniowych',3,7,'fixed','Dzień Płatków Śniadaniowych','National Cereal Day','Święto płatków — najpopularniejszego śniadania.','americas','grain',50,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(102,'dzien-piekarzy-i-cukiernikow',3,15,'fixed','Dzień Piekarzy i Cukierników','Bakers and Confectioners Day','Polskie święto zawodowe piekarzy i cukierników.','poland','grain',56,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(103,'dzien-bez-miesa',3,20,'fixed','Światowy Dzień bez Mięsa','International Day Without Meat','Dzień zachęcający do jednodniowej rezygnacji z mięsa.','global','vegetable',60,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(104,'miedzynarodowy-dzien-gofra',3,25,'fixed','Międzynarodowy Dzień Gofra','International Waffle Day','Szwedzka tradycja obchodzona dziś na całym świecie.','europe','sweet',64,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/","https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(105,'dzien-zelkow',3,28,'fixed','Dzień Żelków','Something on a Stick Day / Gummy Day','Święto słodkich żelowych przysmaków.','americas','sweet',47,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(106,'swiatowy-dzien-muffinka',3,30,'fixed','Światowy Dzień Muffinka','National Muffin Day','Święto babeczek — muffinek.','americas','sweet',52,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(107,'swiatowy-dzien-budyniu',3,31,'fixed','Światowy Dzień Budyniu','National Pudding Day','Święto kremowych deserów.','americas','sweet',44,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(108,'miedzynarodowy-dzien-marchewki',4,4,'fixed','Międzynarodowy Dzień Marchewki','International Carrot Day','Święto najpopularniejszego korzeniowego warzywa.','global','vegetable',54,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/","https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(109,'dzien-czekolady',4,12,'fixed','Dzień Czekolady','Chocolate Day','W Polsce Dzień Czekolady przypada 12 kwietnia.','poland','sweet',86,NULL,'["https://info-day.pl/events/dzien-czekolady/","https://www.filet.pl/kiedy-jest-dzien-czekolady-data-i-ciekawostki/"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(110,'swiatowy-dzien-tunczyka',5,2,'fixed','Światowy Dzień Tuńczyka','World Tuna Day','Ustanowiony przez ONZ, zwraca uwagę na zrównoważone rybołówstwo.','global','seafood',56,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/","https://www.un.org/en/observances"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(111,'swiatowy-dzien-herbaty',5,21,'fixed','Międzynarodowy Dzień Herbaty','International Tea Day','Dzień herbaty wg kalendarza ONZ przypada 21 maja.','global','beverage',80,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/","https://www.un.org/en/observances/tea-day"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(112,'swiatowy-dzien-hamburgera',5,28,'fixed','Światowy Dzień Hamburgera','World Hamburger Day','Święto najsłynniejszej kanapki świata.','americas','dish',76,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/","https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(113,'swiatowy-dzien-soku',5,30,'fixed','Światowy Dzień Soku','World Juice Day','Święto naturalnych soków owocowych i warzywnych.','global','beverage',48,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(114,'swiatowy-dzien-mleka',6,1,'fixed','Światowy Dzień Mleka','World Milk Day','Ustanowiony przez FAO, promuje znaczenie mleka w diecie.','global','dairy',68,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/","https://www.fao.org"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(115,'miedzynarodowy-dzien-falafela',6,12,'fixed','Międzynarodowy Dzień Falafela','International Falafel Day','Święto bliskowschodnich kotlecików z ciecierzycy.','asia','vegetable',58,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(116,'miedzynarodowy-dzien-sushi',6,18,'fixed','Międzynarodowy Dzień Sushi','International Sushi Day','Obchodzony od 2009 r., promuje japońską sztukę kulinarną.','asia','seafood',75,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/","https://internationalsushiday.com"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(117,'dzien-rybaka',6,29,'fixed','Dzień Rybaka','Fisherman''s Day','Polskie święto zawodowe rybaków — dobry dzień na rybną kolację.','poland','seafood',50,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/","https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(118,'miedzynarodowy-dzien-owocow',7,1,'fixed','Międzynarodowy Dzień Owoców','International Fruit Day','Święto świeżych owoców, obchodzone od 2007 r.','global','fruit',62,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(119,'swieto-hot-doga',7,15,'movable','Święto Hot Doga','National Hot Dog Day (US)','Amerykańskie święto parówki w bułce — trzecia środa lipca (w 2026 r. 15 lipca). Ustanowione w 1991 r. przez National Hot Dog and Sausage Council.','americas','meat',66,NULL,'["https://nationaltoday.com/national-hot-dog-day/","https://www.almanac.com/national-hot-dog-day"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(120,'swiatowy-dzien-czekolady',7,7,'fixed','Światowy Dzień Czekolady','World Chocolate Day','Rocznica wprowadzenia czekolady do Europy w 1550 r. — najszczodrzej obchodzone święto czekolady.','global','sweet',95,NULL,'["https://www.tvp.info/94218144/7-lipca-swiatowy-dzien-czekolady","https://www.filet.pl/kiedy-jest-dzien-czekolady-data-i-ciekawostki/"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(121,'dzien-frytek',7,13,'movable','Dzień Frytek','National French Fries Day (US)','Święto złocistych frytek — tradycyjnie 13 lipca, od 2022 r. drugi piątek lipca (w 2026 r. 10 lipca).','americas','vegetable',72,NULL,'["https://nationaldaycalendar.com/celebrations/national-french-fry-day-second-friday-in-july","https://nationaltoday.com/national-french-fry-day/"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(122,'dzien-lodow',7,19,'movable','Dzień Lodów','National Ice Cream Day (US)','Słodkie święto mrożonych deserów — trzecia niedziela lipca (w 2026 r. 19 lipca), ustanowiona przez Ronalda Reagana w 1984 r.','americas','sweet',82,NULL,'["https://nationaldaycalendar.com/celebrations/national-ice-cream-day-third-sunday-in-july","https://nationaltoday.com/national-ice-cream-day/"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(123,'dzien-owocow-lesnych',7,12,'fixed','Dzień Owoców Leśnych','Forest Fruits Day','Święto jagód, borówek i malin — w Polsce szczególnie uzasadnione.','poland','fruit',48,NULL,'["https://kuchniapolska.pl"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(124,'dzien-arbuza',8,3,'fixed','Dzień Arbuza','Watermelon Day','Orzeźwiające święto najpopularniejszego melona wodnego.','americas','fruit',64,NULL,'["https://ua-krakiv.pl/pl/kalendarz-swiat-nietypowych-2026-daty-dni-tygodnia-i-pomysly-na-caly-rok/","https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(125,'dzien-polskiego-miodu',8,8,'fixed','Dzień Polskiego Miodu','Polish Honey Day','Święto polskich miodów odmianowych, promowane przez środowiska pszczelarskie.','poland','sweet',58,NULL,'["https://pszczelarstwo.pl"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(126,'dzien-polskiej-zywnosci',8,25,'fixed','Dzień Polskiej Żywności','Polish Food Day','Święto promujące polską żywność i lokalne produkty — 25 sierpnia.','poland','other',72,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(127,'dzien-ziemniaka',8,19,'fixed','Dzień Ziemniaka','Potato Day','Święto jednego z najważniejszych warzyw polskiej kuchni.','poland','vegetable',62,NULL,'["https://kuchniapolska.pl"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(128,'swiatowy-dzien-jablka',10,21,'fixed','Dzień Jabłka','Apple Day (UK)','Ustanowiony w 1990 r. przez brytyjską organizację Common Ground — święto różnorodności odmian jabłek i sadów. W Polsce, kraju jabłek, szczególnie bliskie.','europe','fruit',66,NULL,'["https://en.wikipedia.org/wiki/List_of_food_days","https://nationaltoday.com/october-21/"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(129,'miedzynarodowy-dzien-kawy',10,1,'fixed','Międzynarodowy Dzień Kawy','International Coffee Day','Obchodzony od 2015 r. z inicjatywy International Coffee Organization.','global','beverage',90,NULL,'["https://www.internationalcoffee.org"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(130,'dzien-kasztana',10,3,'fixed','Dzień Kasztana','Chestnut Day','Jesienne święto kasztanowców — i jadalnych kasztanów.','europe','other',40,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(131,'swiatowy-dzien-osmiornicy',10,8,'fixed','Światowy Dzień Ośmiornicy','World Octopus Day','Święto ośmiornic — i ich obecności w kuchniach świata.','global','seafood',46,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(132,'swiatowy-dzien-zywnosci',10,16,'fixed','Światowy Dzień Żywności','World Food Day','Ustanowiony przez ONZ w rocznicę utworzenia FAO. W Polsce często łączony ze Światowym Dniem Chleba.','global','other',84,NULL,'["https://pl.wikipedia.org/wiki/16_pa%C5%BAdziernika","https://www.fao.org"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(133,'swiatowy-dzien-chleba',10,16,'fixed','Światowy Dzień Chleba','World Bread Day','Ustanowiony przez FAO, promuje znaczenie chleba w kulturach świata.','global','grain',88,NULL,'["https://www.fao.org","https://drukatek.pl/kalendarz-swiat-nietypowych"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(134,'swiatowy-dzien-owocow-i-warzyw',10,16,'fixed','Światowy Dzień Owoców i Warzyw','World Fruit and Vegetables Day','Dzień promujący 5 porcji owoców i warzyw dziennie.','global','vegetable',58,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(135,'dzien-dyni',10,31,'fixed','Dzień Dyni','Pumpkin Day','Jesienne święto dyni — zupy, ciasta i dekoracje.','americas','vegetable',68,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(136,'swiatowy-dzien-makaronu',10,25,'fixed','Światowy Dzień Makaronu','World Pasta Day','Obchodzony od 1995 r. z inicjatywy Światowego Kongresu Makaronu.','global','grain',80,NULL,'["https://www.pastaworldcongress.com"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(137,'dzien-kanapki',11,3,'fixed','Dzień Kanapki','National Sandwich Day','Święto najprostszego posiłku świata.','americas','dish',60,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(138,'swiatowy-dzien-wegan',11,1,'fixed','Światowy Dzień Wegan','World Vegan Day','Propaguje ideę weganizmu i dietę opartą na roślinach.','global','vegetable',64,NULL,'["https://wckwadowice.pl/nietypowe-swieta-w-listopadzie-odkryj-unikalne-tradycje"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(139,'dzien-buraka',11,24,'fixed','Dzień Buraka','Beetroot Day','Święto buraka — od barszczu po ćwikłę.','poland','vegetable',42,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(140,'dzien-ciasta',11,26,'fixed','Dzień Ciasta','National Cake Day','Święto domowych ciast — mazurków, babek i serników.','americas','sweet',70,NULL,'["https://drukatek.pl/kalendarz-swiat-nietypowych","https://www.kalbi.pl/kalendarz-swiat-nietypowych-listopad-2028"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(141,'dzien-dziczyzny',11,10,'fixed','Dzień Dziczyzny','Game Meat Day','Święto mięsa dzikiego, promowane przez polskich myśliwych i restauratorów.','poland','meat',40,NULL,'["https://dziczyzna.pl"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(142,'dzien-piernikow',12,5,'fixed','Dzień Pierników','Gingerbread Day','Święto tradycyjnych pierników — w Polsce szczególnie mocno związane z mikołajkami i Świętami.','europe','sweet',65,NULL,'["https://krakow.pl/z_dawnego_krakowa/277454,1899,komunikat,piernikowe_mikolaje.html"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(143,'dzien-herbaty-grudzien',12,15,'fixed','Dzień Herbaty','International Tea Day (Dec)','Starsza data Dnia Herbaty, wciąż używana w wielu kalendarzach.','global','beverage',74,NULL,'["https://www.un.org/en/observances/tea-day"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(144,'dzien-ryby',12,20,'fixed','Dzień Ryby','Fish Day','Wigilijna tradycja rybnych potraw — karp, śledź i uszka.','poland','seafood',55,NULL,'["https://www.gotowedodruku.pl/produkt/kalendarz-swiat-nietypowych-2026-2027-minimalistyczny-poziomy"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(145,'dzien-tacos',3,31,'fixed','Dzień Taco (Meksyk)','Día del Taco (Mexico)','Meksykańskie święto taco, obchodzone od 2007 r. — 31 marca. W USA National Taco Day od 2024 r. przypada na pierwszy wtorek października.','americas','dish',70,NULL,'["https://fermoctezuma.news/2026/03/30/mexico-celebra-el-dia-del-taco-este-31-de-marzo/","https://nationaltoday.com/national-taco-day/"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(146,'dzien-apple-pie',5,13,'fixed','Dzień Szarlotki','National Apple Pie Day (US)','Amerykańskie święto, w Polsce chętnie łączone z szarlotką.','americas','sweet',55,NULL,'["https://nationaltoday.com"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(147,'dzien-wina',5,25,'fixed','Narodowy Dzień Wina','National Wine Day (US)','Amerykańskie święto wina, globalnie popularne w social media.','americas','beverage',68,NULL,'["https://nationaltoday.com/national-wine-day/"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(148,'miedzynarodowy-dzien-czekolady-wrzesien',9,13,'fixed','Międzynarodowy Dzień Czekolady','International Chocolate Day (Sep)','Trzecie z czekoladowych świąt — 13 września, rocznica urodzin Miltona Hersheya.','americas','sweet',78,NULL,'["https://ua.news/pl/world/sviato-13-veresnia-vidznachaiut-mizhnarodnii-den-shokoladu"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(149,'dzien-pizzy-brazylia',7,10,'fixed','Dzień Pizzy (Brazylia)','Pizza Day (Brazil)','Brazylijska data święta pizzy — 10 lipca, upamiętnia pierwszą wizytę pary królewskiej w pizzerii w 1889 r.','americas','dish',60,NULL,'["https://en.wikipedia.org/wiki/List_of_food_days","https://aracajumagazine.com.br/voce-sabe-quando-e-comemorado-o-dia-mundial-da-pizza-e-como-surgiu/"]',1,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
INSERT INTO "entries" ("id","slug","date_month","date_day","date_type","name_pl","name_en","description_pl","region","category","popularity","image_key","sources","verified","created_at","updated_at","date_end_month","date_end_day","recurrence","entry_year","source_type","created_by","movable_note") VALUES(150,'dzien-pierogi-pazdziernik',10,8,'fixed','Dzień Pierogów','Pierogi Day','Druga, amerykańska data święta pierogów — 8 października.','americas','dish',62,NULL,'["https://www.obscureholidaycalendar.com/holiday/pierogi-day/"]',0,'2026-10-08 21:23:55','2026-10-08 21:23:55',NULL,NULL,'yearly',NULL,'curated',NULL,NULL);
CREATE TABLE popularity_events (
  entry_id INTEGER NOT NULL REFERENCES entries(id),
  event    TEXT NOT NULL CHECK (event IN ('view','detail_open','share')),
  ts       TEXT DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE login_attempts (
  ip_hash TEXT NOT NULL,
  ts      INTEGER NOT NULL
);
INSERT INTO "login_attempts" ("ip_hash","ts") VALUES('73392aa40575d5b640bcd1095a326c10f63fe82f5887d822aaad289213944907',1791524030);
DELETE FROM sqlite_sequence;
INSERT INTO "sqlite_sequence" ("name","seq") VALUES('entries',151);
CREATE INDEX idx_entries_date ON entries(date_month, date_day);
CREATE INDEX idx_entries_region ON entries(region);
CREATE INDEX idx_entries_category ON entries(category);
CREATE INDEX idx_entries_popularity ON entries(popularity DESC);
CREATE INDEX idx_pop_events_entry ON popularity_events(entry_id, ts);
CREATE INDEX idx_entries_source ON entries(source_type);
CREATE INDEX idx_entries_year ON entries(entry_year);
CREATE INDEX idx_login_attempts ON login_attempts(ip_hash, ts);
